language: node_js

node_js:
  - "7"
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov
  # Fix codecov missing deps (issue with node version 8 only)
  - npm install -D has-flag color-convert

install:
  - npm install
  - npm run rollup

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  directories:
    - node_modules
